version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"  # Check for updates daily
    # Optional: Only allow updates to certain actions
    # ignore:
    #   - dependency-name: "actions/checkout"
    #     versions: ["3"]