services:
  hugo:
    image: hugomods/hugo:base
    ports:
      - "1313:1313"  # Expose the Hugo development server on port 1313
    volumes:
      - ".:/src"  # Mount the current directory to /src inside the container
    command: server -D -F # Run the Hugo development server

