name: "Build and Deploy dazz.github.io"
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      # Step 2 - Sets up the latest version of Hugo
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          extended: true
          hugo-version: 'latest'

      # Step 3 - Clean and don't fail
      - name: Clean public directory
        run: rm -rf public/*

      # Step 4 - Builds the site using the latest version of Hugo
      # Also specifies the theme we want to use
      - name: Build
        run: hugo --theme=hugo-ficurinia

      # Step 5 - Create name file
      - name: Create cname file
        run: echo 'dazz.github.io' > public/CNAME

      # Step 6 - Push our generated site to our gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public