name: "Build and Deploy"
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@v2.0.0
        env:
          HUGO_VERSION: 0.109.0
          TARGET_REPO: dazz/dazz.github.io
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUGO_ARGS: '-t hugo-ficurinia'
          CNAME: dazz.github.io